Factor message output in preinit

diff --git a/layout/rootfs-overlay/package/admin/s6-overlay-@VERSION@/libexec/preinit b/layout/rootfs-overlay/package/admin/s6-overlay-@VERSION@/libexec/preinit
--- a/layout/rootfs-overlay/package/admin/s6-overlay-@VERSION@/libexec/preinit
+++ b/layout/rootfs-overlay/package/admin/s6-overlay-@VERSION@/libexec/preinit
@@ -18,6 +18,22 @@
 
 prog=/package/admin/s6-overlay/libexec/preinit
 
+fatal () {
+  echo "$prog: fatal: $*" 1>&2
+}
+
+warning () {
+  if test "0$S6_VERBOSITY" -gt 0 ; then
+    echo "$prog: warning: $*" 1>&2
+  fi
+}
+
+info () {
+  if test "0$S6_VERBOSITY" -gt 1 ; then
+    echo "$prog: info: $*" 1>&2
+  fi
+}
+
 checknoexec () {
   IFS=,
   set -- $1
@@ -33,13 +49,13 @@ checknoexec () {
 
 # Ensure /run is writable
 if test "0$S6_READ_ONLY_ROOT" -ne 0 ; then
-  echo "$prog: info: read-only root" 1>&2
+  info "read-only root"
   if ! test -d /run ; then
-    echo "$prog: fatal: /run is missing or not a directory" 1>&2
+    fatal "/run is missing or not a directory"
     exit 100
   fi
   if : > '/run/test of writability' 2>/dev/null ; then
-    echo "$prog: info: writable /run. Checking for executability." 1>&2
+    info "writable /run. Checking for executability."
     s6-rmrf '/run/test of writability'
     if ! s6-mount -o remount,rw,exec tmpfs /run 2>/dev/null ; then
       notfound=true
@@ -47,23 +63,23 @@ if test "0$S6_READ_ONLY_ROOT" -ne 0 ; then
         if test $filesystem = /run ; then
           notfound=false
           if checknoexec "$options" ; then
-            echo "$prog: warning: your container manager pre-mounts run with \
+            warning "your container manager pre-mounts run with \
 the incorrect noexec option, which s6-overlay cannot work with; expect /init \
 to crash soon. To fix the issue, either pre-mount /run with the exec option, \
 or as a workaround give this container the CAP_SYS_ADMIN capability so \
-s6-overlay can fix it at run time." 1>&2
+s6-overlay can fix it at run time."
           fi
           break
         fi
       done < /proc/mounts
       if $notfound ; then
-        echo "$prog: warning: unable to find /run in /proc/mounts, check that \
+        warning "unable to find /run in /proc/mounts, check that \
 your container manager pre-mounts /proc, and that /run is a tmpfs. The container \
-is likely to crash soon, if /run is (incorrectly) mounted noexec." 1>&2
+is likely to crash soon, if /run is (incorrectly) mounted noexec."
       fi
     fi
   else
-    echo "$prog: info: creating a tmpfs on /run" 1>&2
+    info "creating a tmpfs on /run"
     s6-mount -wt tmpfs -o exec,mode=0755 tmpfs /run
   fi
 else
@@ -72,31 +88,29 @@ fi
 
 eval `s6-overlay-stat /run`
 
-if test "0$S6_VERBOSITY" -gt 1 ; then
-  echo "$prog: info: container permissions: uid=$UID ($USER), euid=$EUID, gid=$GID ($GROUP), egid=$EGID"
-  echo "$prog: info: /run permissions: uid=$uid ($user), gid=$gid ($group), perms=$perms"
-fi
+info "container permissions: uid=$UID ($USER), euid=$EUID, gid=$GID ($GROUP), egid=$EGID"
+info "/run permissions: uid=$uid ($user), gid=$gid ($group), perms=$perms"
 
 if test "$UID" -ne "$uid" ; then  # /run does not belong to the container user
   if test "$EUID" -eq 0 ; then
-    echo "$prog: info: /run belongs to uid $uid instead of $UID - fixing it"
+    info "/run belongs to uid $uid instead of $UID - fixing it"
     s6-chown -U -- /run
     s6-chmod 0755 /run
   elif test "$GID" -eq 0 && test "$gid" -eq 0 ; then
     if echo "$perms" | s6-grep -qF gxgwgr && echo "$perms" | s6-grep -qvF ow ; then
-      echo "$prog: info: using /run with gid 0"
+      info "using /run with gid 0"
     else
-      echo "$prog: fatal: wrong permissions on /run for a gid 0 setup" 
+      fatal "wrong permissions on /run for a gid 0 setup"
       exit 100
     fi
   else
     if test "$gid" -eq "$EGID" ; then x=g ; y=gs ; else x=o ; y= ; fi
     if test "$uid" -eq 0 && echo "$perms" | s6-grep -q "${x}x${x}w${x}r.*os${y}" ; then
-      echo "$prog: warning: /run belongs to uid $uid instead of $UID, but we can still work in single-uid mapping."
+      warning "/run belongs to uid $uid instead of $UID, but we can still work in single-uid mapping."
     elif test "$uid" -eq 0 && echo "$perms" | s6-grep -q "oxoworgxgwgruxuwur" && test "0$S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES" -ne 0 ; then
-      printf "$prog: \e[1;31mwarning\e[0m: /run belongs to uid $uid instead of $UID, \e[1;31mis world writable\e[0m, and we're lacking the privileges to fix it, but we have been instructed to accept it.\n"
+      warning "/run belongs to uid $uid instead of $UID, IS WORLD WRITABLE, and we're lacking the privileges to fix it, but we have been instructed to accept it."
     else
-      echo "$prog: fatal: /run belongs to uid $uid instead of $UID, has insecure and/or unworkable permissions, and we're lacking the privileges to fix it."
+      fatal "/run belongs to uid $uid instead of $UID, has insecure and/or unworkable permissions, and we're lacking the privileges to fix it."
       exit 100
     fi
   fi
@@ -104,7 +118,7 @@ fi
 
 # Ensure /var/run is a symlink to /run
 if test -L /var/run && test "`s6-linkname -f /var/run`" = /run ; then : ; else
-  echo "$prog: notice: /var/run is not a symlink to /run, fixing it" 1>&2
+  warning "/var/run is not a symlink to /run, fixing it"
   s6-rmrf /var/run
   s6-ln -s /run /var/run
 fi
